### ISSUE TITLE
Support matrix

### ISSUE THREAD

**Issue by marocchino** [haya14busa/action-workflow_run-status#465]
#21 is closed, but still not found issue happen on matrix.

```
Run haya14busa/action-workflow_run-status@v1
  with:
    github_token: ***
    requested_as_pending: true
  env:
    ...
    CI_NODE_TOTAL: 4
    PARALLEL_STEPS: 1
    CI_NODE_GROUP: 4
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Error: job not found: System-Test
```

<img width="241" alt="Screenshot 2023-02-15 at 15 26 51" src="https://user-images.githubusercontent.com/128431/218949487-a7c3d4b4-899b-4013-b8c0-cdb4b816b413.png">

I think we need some option for matrix like:

```yaml
jobs:
  post-test-success:
    runs-on: ubuntu-latest
    steps:
      - uses: haya14busa/action-workflow_run-status@v1
        with:
          matrix: ${{ matrix.node_group }}
      - uses: actions/checkout@v2
```
